name: Rust Release Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: rust-build/rust-build.action@v1.4.3
    - name: Release
      run: cargo build --release --verbose --target linux-unknown-musl
